---
# Tasks for creating the agent ISO file
- name: Create the install directory
  ansible.builtin.file:
    path: "{{ openshift_installer_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy template files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/openshift-installer/{{ item | basename }}"
  loop:
    - "install-config.yaml.j2"
    - "agent-config.yaml.j2"

- name: Run openshift-install 
  command: >
    openshift-install agent create
    --dir {{ openshift_installer_dir }}
    --log-level=debug
  register: openshift_install_output
  failed_when: openshift_install_output.rc != 0

- name: Check if the ISO was created
  ansible.builtin.stat:
    path: "{{ openshift_installer_dir }}/agent.iso"
  register: iso_stat

- name: Fail if the ISO was not created
  ansible.builtin.fail:
    msg: "The agent ISO was not created"
  when: not iso_stat.stat.exists