---
- name: Ensure installer directory exists
  ansible.builtin.file:
    path: "{{ openshift_installer_dir }}"
    state: directory
    mode: '0755'

- name: Render install-config.yaml
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ openshift_installer_dir }}/install-config.yaml"
    mode: '0644'

- name: Render agent-config.yaml
  ansible.builtin.template:
    src: agent-config.yaml.j2
    dest: "{{ openshift_installer_dir }}/agent-config.yaml"
    mode: '0644'
