#SPDX-License-Identifier: MIT-0
---
# defaults file for openshift_installer

ocp_version: 4.18
ocp_branch: stable

# OpenShift variables
api_vip: 192.168.1.100
ingress_vip: 192.168.1.101
base_domain: example.com
worker_nodes_count: 0
master_nodes_count: 1
cluster_name: my-cluster
machine_cidr: 192.168.1.0/24
openshift_ssh_key: <ssh_key>

sno: true

# BMC Variables
bmc_username: admin
bmc_password: password

ipmi: false
redfish: true

name_servers:
  - 192.168.1.1
  - 192.168.1.2
gateway_ip: 192.168.1.1

# Node Info
baremetal_master_nodes:
  - hostname: master-1
    nics:
      - name: "ens3"
        ip: 192.168.1.110
        mac: 00:11:22:33:44:55
        dhcp: true
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password
  - hostname: master-2
    nics:
      - name: "ens3"
        ip: 192.168.1.111
        mac: 00:11:22:33:44:56
        dhcp: true
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password
  - hostname: master-3
    nics:
      - name: "ens3"
        ip: 192.168.1.112
        dhcp: true
        mac: 00:11:22:33:44:57
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password
# Node Info
baremetal_worker_nodes:
  - hostname: worker-1
    nics:
      - name: "ens3"
        ip: 192.168.1.120
        mac: 00:11:22:33:44:58
        dhcp: true
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password
  - hostname: worker-2
    nics:
      - name: "ens3"
        ip: 192.168.1.121
        mac: 00:11:22:33:44:59
        dhcp: true
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password
  - hostname: worker-3
    nics:
      - name: "ens3"
        ip: 192.168.1.122
        dhcp: true
        mac: 00:11:22:33:44:60
    install_disk: /dev/sda
    bmc:
      address: 192.168.1.100
      username: admin
      password: password

# Agent Config Vars
rendezvous_ip: 192.168.1.102
